# Generated by Django 5.0.1 on 2025-12-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('features', models.JSONField(default=list, verbose_name='ویژگی\u200cها')),
                ('pricing', models.JSONField(default=dict, verbose_name='قیمت\u200cگذاری')),
                ('gallery', models.JSONField(default=list, verbose_name='گالری تصاویر')),
                ('specifications', models.JSONField(default=list, verbose_name='مشخصات فنی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات متا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['-created_at'],
            },
        ),
    ]
