# Generated by Django 5.0.1 on 2025-12-07 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='ایمیل مشتری')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='تلفن مشتری')),
                ('service_type', models.CharField(max_length=100, verbose_name='نوع سرویس')),
                ('project_details', models.TextField(verbose_name='جزئیات پروژه')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='بودجه تقریبی')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='مهلت تحویل')),
                ('files', models.JSONField(blank=True, default=list, verbose_name='فایل‌های پیوست')),
                ('special_requirements', models.TextField(blank=True, verbose_name='نیازهای خاص')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('processing', 'در حال پردازش'), ('designing', 'در حال طراحی'), ('printing', 'در حال چاپ'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت‌های ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست قیمت',
                'verbose_name_plural': 'درخواست‌های قیمت',
                'ordering': ['-created_at'],
            },
        ),
    ]
