# Generated by Django 5.0.1 on 2025-12-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('client', models.CharField(max_length=200, verbose_name='مشتری')),
                ('year', models.IntegerField(verbose_name='سال اجرا')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('challenge', models.TextField(blank=True, verbose_name='چالش')),
                ('solution', models.TextField(blank=True, verbose_name='راهکار')),
                ('result', models.TextField(blank=True, verbose_name='نتیجه')),
                ('images', models.JSONField(default=list, verbose_name='تصاویر')),
                ('tags', models.JSONField(default=list, verbose_name='تگ\u200cها')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات متا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
                'ordering': ['-created_at'],
            },
        ),
    ]
