# Generated by Django 5.0.1 on 2025-11-29 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'آدرس کاربر', 'verbose_name_plural': 'آدرس\u200cهای کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل\u200cهای کاربران'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP ورود'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='تلاش\u200cهای ناموفق ورود'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='موبایل تایید شده'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='احراز هویت دو مرحله\u200cای'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'منزل'), ('office', 'محل کار'), ('warehouse', 'انبار'), ('other', 'سایر')], default='home', max_length=20, verbose_name='نوع آدرس'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام گیرنده'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبایل گیرنده'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='economic_code',
            field=models.CharField(blank=True, max_length=14, verbose_name='کد اقتصادی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='iban',
            field=models.CharField(blank=True, help_text='IR...', max_length=26, verbose_name='شماره شبا'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=11, verbose_name='شناسه ملی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره ثبت'),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('register', 'ثبت\u200cنام'), ('verify', 'تایید'), ('reset_password', 'بازیابی رمز')], max_length=20, verbose_name='هدف')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کد یکبار مصرف',
                'verbose_name_plural': 'کدهای یکبار مصرف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'ورود موفق'), ('login_failed', 'ورود ناموفق'), ('logout', 'خروج'), ('password_changed', 'تغییر رمز'), ('password_reset', 'بازیابی رمز'), ('email_changed', 'تغییر ایمیل'), ('phone_changed', 'تغییر موبایل'), ('2fa_enabled', 'فعال\u200cسازی 2FA'), ('2fa_disabled', 'غیرفعال\u200cسازی 2FA'), ('suspicious_activity', 'فعالیت مشکوک')], max_length=50, verbose_name='عملیات')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ امنیتی',
                'verbose_name_plural': 'لاگ\u200cهای امنیتی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('sales', 'فروش'), ('production', 'تولید'), ('finance', 'مالی'), ('support', 'پشتیبانی'), ('management', 'مدیریت')], max_length=20, verbose_name='بخش')),
                ('position', models.CharField(choices=[('manager', 'مدیر'), ('operator', 'اپراتور'), ('assistant', 'دستیار')], max_length=20, verbose_name='سمت')),
                ('can_view_orders', models.BooleanField(default=True, verbose_name='مشاهده سفارشات')),
                ('can_edit_orders', models.BooleanField(default=False, verbose_name='ویرایش سفارشات')),
                ('can_edit_prices', models.BooleanField(default=False, verbose_name='ویرایش قیمت\u200cها')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='مدیریت کاربران')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='مشاهده گزارشات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True, verbose_name='کلید نشست')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_type', models.CharField(choices=[('mobile', 'موبایل'), ('desktop', 'دسکتاپ'), ('tablet', 'تبلت'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='نوع دستگاه')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='موقعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نشست کاربر',
                'verbose_name_plural': 'نشست\u200cهای کاربران',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='واحد پول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('refund', 'بازگشت وجه'), ('purchase', 'خرید'), ('bonus', 'جایزه')], max_length=20, verbose_name='نوع')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userwallet')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at'],
            },
        ),
    ]
