# Generated by Django 5.0.1 on 2025-11-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraddress_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_read_customer', 'می\u200cتواند مشتریان را مشاهده کند'), ('can_update_customer', 'می\u200cتواند مشتریان را ویرایش کند'), ('can_delete_customer', 'می\u200cتواند مشتریان را حذف کند')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='login_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='receiver_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='economic_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='آواتار'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_store_admin',
            field=models.BooleanField(default=False, verbose_name='مدیر فروشگاه'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_store_staff',
            field=models.BooleanField(default=False, verbose_name='کارمند فروشگاه'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'مشتری'), ('ADMIN', 'مدیر کل'), ('ORDER_PROCESSOR', 'پردازشگر سفارشات')], default='CUSTOMER', max_length=50, verbose_name='نقش'),
        ),
        migrations.DeleteModel(
            name='OTPCode',
        ),
        migrations.DeleteModel(
            name='SecurityLog',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
