# Generated by Django 5.0.1 on 2025-11-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_securitylog_user_remove_teammember_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='آواتار'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('admin', 'مدیر کل'), ('staff', 'کارمند'), ('manager', 'مدیر')], default='customer', max_length=50, verbose_name='نقش'),
        ),
    ]
