# Generated by Django 5.0.1 on 2025-12-03 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wallet_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'ورود موفق'), ('login_failed', 'ورود ناموفق'), ('logout', 'خروج'), ('password_changed', 'تغییر رمز عبور'), ('password_reset', 'بازیابی رمز عبور'), ('email_changed', 'تغییر ایمیل'), ('phone_changed', 'تغییر موبایل'), ('suspicious_activity', 'فعالیت مشکوک')], max_length=50, verbose_name='عملیات')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ امنیتی',
                'verbose_name_plural': 'لاگ\u200cهای امنیتی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='کلید نشست')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آی\u200cپی')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='نوع دستگاه')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='موقعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نشست کاربر',
                'verbose_name_plural': 'نشست\u200cهای کاربر',
                'ordering': ['-last_activity'],
            },
        ),
    ]
