# Generated by Django 5.0.1 on 2025-11-30 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاغذ')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('gram_weight', models.PositiveIntegerField(verbose_name='گرماژ')),
                ('price_per_sheet', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='قیمت هر برگ')),
                ('is_fancy', models.BooleanField(default=False, verbose_name='کاغذ فانتزی')),
                ('texture', models.CharField(blank=True, max_length=100, verbose_name='بافت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='papers/', verbose_name='تصویر نمونه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع کاغذ',
                'verbose_name_plural': 'انواع کاغذ',
                'ordering': ['gram_weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر اصلی')),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='گالری تصاویر')),
                ('print_type', models.CharField(choices=[('digital', 'چاپ دیجیتال'), ('offset', 'چاپ افست'), ('both', 'هر دو')], default='digital', max_length=10, verbose_name='نوع چاپ')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='حداقل تیراژ')),
                ('max_quantity', models.PositiveIntegerField(default=10000, verbose_name='حداکثر تیراژ')),
                ('delivery_time_hours', models.PositiveIntegerField(default=24, verbose_name='زمان تحویل (ساعت)')),
                ('has_design_service', models.BooleanField(default=True, verbose_name='خدمات طراحی')),
                ('has_online_calculator', models.BooleanField(default=True, verbose_name='ماشین حساب آنلاین')),
                ('has_file_upload', models.BooleanField(default=True, verbose_name='آپلود فایل')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت پایه')),
                ('price_per_extra', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت هر واحد اضافی')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات SEO')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'محصول چاپی',
                'verbose_name_plural': 'محصولات چاپی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('confirmed', 'تأیید شده'), ('in_progress', 'در حال انجام'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('contact_name', models.CharField(max_length=100, verbose_name='نام تماس')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='تلفن تماس')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='ایمیل تماس')),
                ('delivery_address', models.TextField(verbose_name='آدرس تحویل')),
                ('delivery_city', models.CharField(max_length=50, verbose_name='شهر')),
                ('delivery_postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('delivery_method', models.CharField(default='پیک', max_length=50, verbose_name='نحوه تحویل')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('urgent_order', models.BooleanField(default=False, verbose_name='سفارش فوری')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='جمع کل')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='تخفیف')),
                ('delivery_cost', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='هزینه ارسال')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ نهایی')),
                ('design_files', models.FileField(blank=True, null=True, upload_to='orders/designs/', verbose_name='فایل طراحی')),
                ('customer_notes', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(verbose_name='حداقل تعداد')),
                ('max_quantity', models.PositiveIntegerField(verbose_name='حداکثر تعداد')),
                ('price_per_unit', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='قیمت هر واحد')),
                ('has_lamination', models.BooleanField(default=False, verbose_name='لمینت')),
                ('has_uv', models.BooleanField(default=False, verbose_name='UV')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('paper_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.papertype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='products.product')),
            ],
            options={
                'verbose_name': 'قانون قیمت\u200cگذاری',
                'verbose_name_plural': 'قوانین قیمت\u200cگذاری',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='قیمت واحد')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت کل')),
                ('size_width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='عرض (سانتی\u200cمتر)')),
                ('size_height', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ارتفاع (سانتی\u200cمتر)')),
                ('has_lamination', models.BooleanField(default=False, verbose_name='لمینت')),
                ('has_uv_coating', models.BooleanField(default=False, verbose_name='پوشش UV')),
                ('include_design', models.BooleanField(default=False, verbose_name='شامل طراحی')),
                ('special_instructions', models.TextField(blank=True, verbose_name='دستورالعمل\u200cهای خاص')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
                ('paper_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.papertype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محصول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_files/', verbose_name='فایل')),
                ('original_name', models.CharField(max_length=255, verbose_name='نام اصلی فایل')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع فایل')),
                ('file_size', models.PositiveIntegerField(verbose_name='حجم فایل (بایت)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='user_files/thumbnails/', verbose_name='تصویر بندانگشتی')),
                ('status', models.CharField(default='uploaded', max_length=20, verbose_name='وضعیت')),
                ('processing_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای پردازش')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فایل آپلود شده',
                'verbose_name_plural': 'فایل\u200cهای آپلود شده',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.papertype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_types', to='products.product')),
            ],
            options={
                'verbose_name': 'کاغذ محصول',
                'verbose_name_plural': 'کاغذهای محصول',
                'unique_together': {('product', 'paper_type')},
            },
        ),
    ]
